site_name: kuma DATA

nav:
    - 'index.md'
    - 'ds_dev.md'

theme:
  name: material
  language: 'ja'
  font: 
    text: IBM+Plex+Sans+JP
  palette:
    scheme: slate
    primary: black
    accent: light green
  extra:
    search:
      language: 'jp'

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
      ##clickable_checkbox: true
  - def_list